export const entityDB = <Entity[]>[
  { id: 'album', label: 'Álbum', icon: 'icon-park-outline:folder-music-one' },
  { id: 'podcast', label: 'Podcast', icon: 'icon-park-outline:microphone' },
  {
    id: 'audiobook',
    label: 'Audiolibro',
    icon: 'icon-park-outline:headphone-sound',
  },
];

export const marketDB = <Market[]>[
  { id: 'ae', label: 'United Arab Emirates' },
  { id: 'ag', label: 'Antigua and Barbuda' },
  { id: 'ai', label: 'Anguilla' },
  { id: 'al', label: 'Albania' },
  { id: 'am', label: 'Armenia' },
  { id: 'ao', label: 'Angola' },
  { id: 'ar', label: 'Argentina' },
  { id: 'at', label: 'Austria' },
  { id: 'au', label: 'Australia' },
  { id: 'az', label: 'Azerbaijan' },
  { id: 'bb', label: 'Barbados' },
  { id: 'be', label: 'Belgium' },
  { id: 'bf', label: 'Burkina-Faso' },
  { id: 'bg', label: 'Bulgaria' },
  { id: 'bh', label: 'Bahrain' },
  { id: 'bj', label: 'Benin' },
  { id: 'bm', label: 'Bermuda' },
  { id: 'bn', label: 'Brunei Darussalam' },
  { id: 'bo', label: 'Bolivia' },
  { id: 'br', label: 'Brazil' },
  { id: 'bs', label: 'Bahamas' },
  { id: 'bt', label: 'Bhutan' },
  { id: 'bw', label: 'Botswana' },
  { id: 'by', label: 'Belarus' },
  { id: 'bz', label: 'Belize' },
  { id: 'ca', label: 'Canada' },
  { id: 'cg', label: 'Democratic Republic of the Congo' },
  { id: 'ch', label: 'Switzerland' },
  { id: 'cl', label: 'Chile' },
  { id: 'cn', label: 'China' },
  { id: 'co', label: 'Colombia' },
  { id: 'cr', label: 'Costa Rica' },
  { id: 'cv', label: 'Cape Verde' },
  { id: 'cy', label: 'Cyprus' },
  { id: 'cz', label: 'Czech Republic' },
  { id: 'de', label: 'Germany' },
  { id: 'dk', label: 'Denmark' },
  { id: 'dm', label: 'Dominica' },
  { id: 'do', label: 'Dominican Republic' },
  { id: 'dz', label: 'Algeria' },
  { id: 'ec', label: 'Ecuador' },
  { id: 'ee', label: 'Estonia' },
  { id: 'eg', label: 'Egypt' },
  { id: 'es', label: 'Spain' },
  { id: 'fi', label: 'Finland' },
  { id: 'fj', label: 'Fiji' },
  { id: 'fm', label: 'Federated States of Micronesia' },
  { id: 'fr', label: 'France' },
  { id: 'gb', label: 'United Kingdom' },
  { id: 'gd', label: 'Grenada' },
  { id: 'gh', label: 'Ghana' },
  { id: 'gm', label: 'Gambia' },
  { id: 'gr', label: 'Greece' },
  { id: 'gt', label: 'Guatemala' },
  { id: 'gw', label: 'Guinea Bissau' },
  { id: 'gy', label: 'Guyana' },
  { id: 'hk', label: 'Hong Kong' },
  { id: 'hn', label: 'Honduras' },
  { id: 'hr', label: 'Croatia' },
  { id: 'hu', label: 'Hungary' },
  { id: 'id', label: 'Indonesia' },
  { id: 'ie', label: 'Ireland' },
  { id: 'il', label: 'Israel' },
  { id: 'in', label: 'India' },
  { id: 'is', label: 'Iceland' },
  { id: 'it', label: 'Italy' },
  { id: 'jm', label: 'Jamaica' },
  { id: 'jo', label: 'Jordan' },
  { id: 'jp', label: 'Japan' },
  { id: 'ke', label: 'Kenya' },
  { id: 'kg', label: 'Krygyzstan' },
  { id: 'kh', label: 'Cambodia' },
  { id: 'kn', label: 'Saint Kitts and Nevis' },
  { id: 'kr', label: 'South Korea' },
  { id: 'kw', label: 'Kuwait' },
  { id: 'ky', label: 'Cayman Islands' },
  { id: 'kz', label: 'Kazakhstan' },
  { id: 'la', label: 'Laos' },
  { id: 'lb', label: 'Lebanon' },
  { id: 'lc', label: 'Saint Lucia' },
  { id: 'lk', label: 'Sri Lanka' },
  { id: 'lr', label: 'Liberia' },
  { id: 'lt', label: 'Lithuania' },
  { id: 'lu', label: 'Luxembourg' },
  { id: 'lv', label: 'Latvia' },
  { id: 'md', label: 'Moldova' },
  { id: 'mg', label: 'Madagascar' },
  { id: 'mk', label: 'Macedonia' },
  { id: 'ml', label: 'Mali' },
  { id: 'mn', label: 'Mongolia' },
  { id: 'mo', label: 'Macau' },
  { id: 'mr', label: 'Mauritania' },
  { id: 'ms', label: 'Montserrat' },
  { id: 'mt', label: 'Malta' },
  { id: 'mu', label: 'Mauritius' },
  { id: 'mw', label: 'Malawi' },
  { id: 'mx', label: 'Mexico' },
  { id: 'my', label: 'Malaysia' },
  { id: 'mz', label: 'Mozambique' },
  { id: 'na', label: 'Namibia' },
  { id: 'ne', label: 'Niger' },
  { id: 'ng', label: 'Nigeria' },
  { id: 'ni', label: 'Nicaragua' },
  { id: 'nl', label: 'Netherlands' },
  { id: 'np', label: 'Nepal' },
  { id: 'no', label: 'Norway' },
  { id: 'nz', label: 'New Zealand' },
  { id: 'om', label: 'Oman' },
  { id: 'pa', label: 'Panama' },
  { id: 'pe', label: 'Peru' },
  { id: 'pg', label: 'Papua New Guinea' },
  { id: 'ph', label: 'Philippines' },
  { id: 'pk', label: 'Pakistan' },
  { id: 'pl', label: 'Poland' },
  { id: 'pt', label: 'Portugal' },
  { id: 'pw', label: 'Palau' },
  { id: 'py', label: 'Paraguay' },
  { id: 'qa', label: 'Qatar' },
  { id: 'ro', label: 'Romania' },
  { id: 'ru', label: 'Russia' },
  { id: 'sa', label: 'Saudi Arabia' },
  { id: 'sb', label: 'Soloman Islands' },
  { id: 'sc', label: 'Seychelles' },
  { id: 'se', label: 'Sweden' },
  { id: 'sg', label: 'Singapore' },
  { id: 'si', label: 'Slovenia' },
  { id: 'sk', label: 'Slovakia' },
  { id: 'sl', label: 'Sierra Leone' },
  { id: 'sn', label: 'Senegal' },
  { id: 'sr', label: 'Surilabel' },
  { id: 'st', label: 'Sao Tome e Principe' },
  { id: 'sv', label: 'El Salvador' },
  { id: 'sz', label: 'Swaziland' },
  { id: 'tc', label: 'Turks and Caicos Islands' },
  { id: 'td', label: 'Chad' },
  { id: 'th', label: 'Thailand' },
  { id: 'tj', label: 'Tajikistan' },
  { id: 'tm', label: 'Turkmenistan' },
  { id: 'tn', label: 'Tunisia' },
  { id: 'tr', label: 'Turkey' },
  { id: 'tt', label: 'Republic of Trinidad and Tobago' },
  { id: 'tw', label: 'Taiwan' },
  { id: 'tz', label: 'Tanzania' },
  { id: 'ua', label: 'Ukraine' },
  { id: 'ug', label: 'Uganda' },
  { id: 'us', label: 'United States of America' },
  { id: 'uy', label: 'Uruguay' },
  { id: 'uz', label: 'Uzbekistan' },
  { id: 'vc', label: 'Saint Vincent and the Grenadines' },
  { id: 've', label: 'Venezuela' },
  { id: 'vg', label: 'British Virgin Islands' },
  { id: 'vn', label: 'Vietnam' },
  { id: 'ye', label: 'Yemen' },
  { id: 'za', label: 'South Africa' },
  { id: 'zw', label: 'Zimbabwe' },
];
